import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'Go to Registration' }).click();
  await page.getByLabel('CPF').click();
  await page.getByLabel('CPF').fill('111.111.111-111');
  await page.getByLabel('CPF').press('Tab');
  await page.getByLabel('Nome').fill('teste da Silva');
  await page.getByLabel('Nome').press('Tab');
  await page.getByLabel('Data de Nascimento').fill('1997-05-12');
  await page.getByLabel('Data de Nascimento').press('Tab');
  await page.getByLabel('Email').fill('teste@email.com');
  await page.getByLabel('Email').press('Tab');
  await page.getByLabel('Telefone Celular').fill('(11) 11111-11111');
  await page.getByLabel('Telefone Celular').press('Tab');
  await page.getByLabel('CEP').fill('22620-200');
  await expect(page.getByLabel('CEP')).toBeVisible();
  await page.getByLabel('Rua').click();
  await expect(page.getByLabel('Rua')).toBeVisible();
  await expect(page.getByLabel('Rua')).toHaveValue('Rua Sanharó');
  await expect(page.getByLabel('Bairro')).toHaveValue('Barra da Tijuca');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByLabel('Número').click();
  await page.getByLabel('Número').fill('123');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('combobox').selectOption('acfdb825-3a85-4b50-9da1-20c22915fb0f');
  await page.locator('div').filter({ hasText: /^Tem plano de saúdeNãoSim$/ }).locator('div').nth(1).click();
  await page.locator('input[name="\\30 "]').nth(1).check();
  await page.locator('form div').filter({ hasText: 'Tem plano de saúdeNã' }).getByRole('combobox').selectOption('Operadora 1');
  await page.locator('div').filter({ hasText: /^PlanoSelecionePlano A1Plano B1Plano C1$/ }).getByRole('combobox').selectOption('Plano A1');
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('11111111');
  await page.locator('div').filter({ hasText: /^Alergias a MedicamentosNãoSim$/ }).locator('div').nth(1).click();
  await page.locator('input[name="\\33 "]').nth(1).check();
  await page.locator('div').filter({ hasText: /^Penicilina$/ }).getByRole('checkbox').check();
  await page.locator('div').filter({ hasText: /^Sulfa$/ }).getByRole('checkbox').check();
  await page.locator('input[name="\\34 "]').nth(1).check();
  await page.locator('div').filter({ hasText: /^Hipertesão arterial$/ }).getByRole('checkbox').check();
  await page.getByText('Diabetes').click();
  await page.locator('div').filter({ hasText: /^Diabetes$/ }).getByRole('checkbox').check();
  await page.locator('div').filter({ hasText: /^Diabetes$/ }).getByRole('checkbox').uncheck();
  await page.locator('input[name="\\35 "]').nth(1).check();
  await page.locator('div').filter({ hasText: /^Tipo de Câncer$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Tipo de Câncer$/ }).getByRole('textbox').fill('coracao');
  await page.locator('div').filter({ hasText: /^Tipo de Câncer$/ }).getByRole('textbox').press('Tab');
  await page.locator('input[name="\\35 \\.1"]').first().press('Tab');
  await page.locator('input[name="\\35 \\.1"]').nth(1).check();
  await page.locator('input[type="date"]').fill('2020-02-20');
  await page.locator('input[type="date"]').press('Tab');
  await page.locator('input[name="\\35 \\.2"]').first().press('Tab');
  await page.locator('div').filter({ hasText: /^RadioterapiaNãoSim$/ }).locator('div').nth(1).click();
  await page.locator('input[name="\\35 \\.2"]').nth(1).check();
  await page.locator('div').filter({ hasText: /^RadioterapiaNãoSimData de última Radioterapia$/ }).getByRole('textbox').fill('2020-02-20');
  await page.locator('input[name="\\36 "]').nth(1).check();
  await page.locator('div').filter({ hasText: /^Nome do Medicamento$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Nome do Medicamento$/ }).getByRole('textbox').fill('tsete');
  await page.locator('div').filter({ hasText: /^Dose$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Dose$/ }).getByRole('textbox').fill('123');
  await page.locator('div').filter({ hasText: /^Quantas vezes ao dia$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Quantas vezes ao dia$/ }).getByRole('textbox').fill('123');
  await page.locator('input[name="\\37 "]').nth(1).check();
  await page.locator('div').filter({ hasText: /^Motivo da Internação$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Motivo da Internação$/ }).getByRole('textbox').fill('dodoi');
  await page.locator('div').filter({ hasText: /^Motivo da Internação$/ }).getByRole('textbox').press('Tab');
  await page.locator('div').filter({ hasText: /^Data da Internação$/ }).getByRole('textbox').fill('2020-02-20');
  await page.locator('div').filter({ hasText: /^Data da Internação$/ }).getByRole('textbox').press('Tab');
  await page.locator('div').filter({ hasText: /^Data de alta$/ }).getByRole('textbox').fill('2020-02-20');
  await page.locator('div').filter({ hasText: /^Data de alta$/ }).getByRole('textbox').press('ArrowRight');
  await page.locator('div').filter({ hasText: /^Data de alta$/ }).getByRole('textbox').fill('2020-03-10');
  await page.getByRole('button', { name: 'Submit' }).click();
});